apiVersion: apps/v1
kind: Deployment
metadata:
  name: oe-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oe-nodejs
  template:
    metadata:
      labels:
        app: oe-nodejs
    spec:
      containers:
      - name:  oe-nodejs
        image:  neroxxpips/nodejs:latest
        ports:
        - containerPort: 3000
