name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY_URL: 'https://registry-1.docker.io/v2/'
  DOCKER_REGISTRY: 'neroxxpips'
  DOCKER_IMAGE_NAME: 'oe-nodejs2'
  DOCKER_IMAGE_TAG: 'latest'
  DOCKER_PASSWORD: ${{ secrets.DOCKERPASSWORD }}
  DOCKER_USERNAME: 'neroxxpips'
  NAMESPACE: 'oe-github'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:$DOCKER_IMAGE_TAG .

      - name: Log in to Docker registry and Push Docker Image
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:$DOCKER_IMAGE_TAG

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Configure kubectl
        run: aws eks --region $REGION update-kubeconfig --name $CLUSTER_NAME

      - name: Deploy to EKS
        run: |
          sed -i 's/name_space/$NAMESPACE/' deploy/namespace.yaml
          kubectl apply -f deploy/namespace.yaml
          kubectl apply -f deploy/deployment.yaml -f deploy/service.yaml -n $NAMEPACES

      